INSERT INTO movies (id, title, release_date, trailer_link, poster) VALUES
(1, 'Oppenheimer', '2023-07-21', 'https://www.youtube.com/watch?v=uYPbbksJxIg', 'https://www.themoviedb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
(2, 'Barbie', '2023-07-21', 'https://www.youtube.com/watch?v=pBk4NYhWNMM', 'https://www.themoviedb.org/t/p/original/cgYg04miVQUAG2FKk3amSnnHzOp.jpg'),
(3, 'Spider-Man: Across the Spider-Verse', '2023-06-01', 'https://www.youtube.com/watch?v=shW9i6k8cB0', 'https://www.themoviedb.org/t/p/original/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'),
(4, 'Interstellar', '2014-11-07', 'https://www.youtube.com/watch?v=2LqzF5WauAw', 'https://www.themoviedb.org/t/p/original/4pWbfjzUkusGXAZQoduARaI0qu2.jpg'),
(5, 'Zack Snyder\'s Justice League', '2021-03-18', 'https://www.youtube.com/watch?v=ui37YKQ9AC4', 'https://www.themoviedb.org/t/p/original/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg'),
(6, 'Inception', '2010-07-16', 'https://www.youtube.com/watch?v=JE9z-gy4De4', 'https://www.themoviedb.org/t/p/original/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg'),
(7, 'The Batman', '2022-03-04', 'https://www.youtube.com/watch?v=vc7_mH2PWHs', 'https://www.themoviedb.org/t/p/original/seyWFgGInaLqW7nOZvu0ZC95rtx.jpg'),
(8, 'Black Adam', '2022-10-19', 'https://www.youtube.com/watch?v=JaV7mmc9HGw', 'https://image.tmdb.org/t/p/original/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg'),
(9, 'Spider-Man: No Way Home', '2021-12-17', 'https://www.youtube.com/watch?v=1mTjfMFyPi8', 'https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg'),
(10, 'Black Panther: Wakanda Forever', '2022-11-11', 'https://www.youtube.com/watch?v=_Z3QKkl1WyM', 'https://image.tmdb.org/t/p/original/cryEN3sWlgB2wTzcUNVtDGI8bkM.jpg');

INSERT INTO movie_genres (genres, movie_id) VALUES
('Drama', 1),
('History', 1),
('Comedy', 2),
('Adventure', 2),
('Fantasy', 2),
('Action', 3),
('Adventure',3),
('Animation', 3),
('Science', 3),
('Fiction', 3),
('Adventure', 4),
('Drama', 4),
('Science Fiction', 4),
('Action', 5),
('Adventure', 5),
('Fantasy', 5),
('Action', 6),
('Science Fiction', 6),
('Adventure', 6),
('Crime', 7),
('Mystery', 7),
('Thriller', 7),
('Fantasy', 8),
('Action', 8),
('Science Fiction', 8),
('Action', 9),
('Adventure', 9),
('Science Fiction', 9),
('Action', 10),
('Adventure', 10),
('Science Fiction', 10);

INSERT INTO movie_backdrops (backdrops, movie_id) VALUES
('https://www.themoviedb.org/t/p/original/yNMgBF92CfD5ILvePt6nIy3OYdm.jpg', 1),
('https://www.themoviedb.org/t/p/original/xcXALwBjdHIjrESpGVhghqj8fGT.jpg', 1),
('https://www.themoviedb.org/t/p/original/bBvlI3Vmh0tcqyAUfKKRNHHA07V.jpg', 1),
('https://www.themoviedb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg', 1),
('https://www.themoviedb.org/t/p/original/tTGrsY9RUv55V0TMXFCPpWymS6a.jpg', 1),
('https://www.themoviedb.org/t/p/original/eF4gVoHnbE1NbmkDMXCOxa0dMCh.jpg', 1),
('https://www.themoviedb.org/t/p/original/gWc3ztjgsuUddZOBs5aSuvaM6uo.jpg', 1),
('https://www.themoviedb.org/t/p/original/mm7qW1zO1jYWMFFBk9qf73HMhUJ.jpg', 1),
('https://www.themoviedb.org/t/p/original/8szKvTWhqnatqrHWloFyyPX1WZc.jpg', 1),
('https://www.themoviedb.org/t/p/original/fjg2gQTprfDpNH05RboXQzsZwez.jpg', 1),
('https://www.themoviedb.org/t/p/original/nHf61UzkfFno5X1ofIhugCPus2R.jpg', 2),
('https://www.themoviedb.org/t/p/original/llZSAx6YW0y9tV4iMKmbUBNh70I.jpg', 2),
('https://www.themoviedb.org/t/p/original/v3gfn7147bmp776ouWRUL3j3viV.jpg', 2),
('https://www.themoviedb.org/t/p/original/1esAE8sLJRWWFsLLeh5r3g2WanI.jpg', 2),
('https://www.themoviedb.org/t/p/original/tTfnd2VrlaZJSBD9HUbtSF3CqPJ.jpg', 2),
('https://www.themoviedb.org/t/p/original/14EfaWsbn4XVrl8LMsAxAM5sjZb.jpg', 2),
('https://www.themoviedb.org/t/p/original/uvaXVadrn3YPKFP1stA60k1jXi5.jpg', 2),
('https://www.themoviedb.org/t/p/original/lL0N8Gb5tHSHi8Voda7kii2BVPc.jpg', 2),
('https://www.themoviedb.org/t/p/original/cQzFKlLZPcmG4iAH3c4iuPNOqNd.jpg', 2),
('https://www.themoviedb.org/t/p/original/fRyYKQdsXIjw26MendWxpWmvnBs.jpg', 2),
('https://www.themoviedb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg', 3),
('https://www.themoviedb.org/t/p/original/gwE7DBdhm565GmXp0WiplxseiLv.jpg', 3),
('https://www.themoviedb.org/t/p/original/3igTCivZPVaR8SaZYKUf3w3V2U.jpg', 3),
('https://www.themoviedb.org/t/p/original/9xfDWXAUbFXQK585JvByT5pEAhe.jpg', 3),
('https://www.themoviedb.org/t/p/original/rsaSxTYH85f7JJmbDv0wz7CIOes.jpg', 3),
('https://www.themoviedb.org/t/p/original/kGWpZewzInbzTuaIHcy0bFgzXuM.jpg', 3),
('https://www.themoviedb.org/t/p/original/rxav3SDsDRzRs4ait1lI6OIrJBH.jpg', 3),
('https://www.themoviedb.org/t/p/original/7Y8qI6AD15kgMYgu50dpEInojrn.jpg', 3),
('https://www.themoviedb.org/t/p/original/dlebyCnmdwXtJfHNicBYhudz5EJ.jpg', 3),
('https://www.themoviedb.org/t/p/original/6j6HpKRZKw0RP7bRX5Q45qaWsAX.jpg', 3),
('https://www.themoviedb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg', 4),
('https://www.themoviedb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg', 4),
('https://www.themoviedb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', 4),
('https://www.themoviedb.org/t/p/original/5C3RriLKkIAQtQMx85JLtu4rVI2.jpg', 4),
('https://www.themoviedb.org/t/p/original/i2gJQtnkLA2SpU9cRvkbuLOoW1I.jpg', 4),
('https://www.themoviedb.org/t/p/original/wqBlk1ejN71gzKvlbXYrC1FfdsY.jpg', 4),
('https://www.themoviedb.org/t/p/original/hiU41Xve67Ay3lOwBYTuZSV5ssO.jpg', 4),
('https://www.themoviedb.org/t/p/original/9mmkq59uRuJWDFz9UHeX5ATNJYf.jpg', 4),
('https://www.themoviedb.org/t/p/original/vXMNOMkRhqrtsSZY6nCGCMkRslM.jpg', 4),
('https://www.themoviedb.org/t/p/original/Ab9eQH5O3VCTQjJsQghxjYOkfMp.jpg', 4),
('https://www.themoviedb.org/t/p/original/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg', 5),
('https://www.themoviedb.org/t/p/original/hjypZf7Juayon8emI6HNSyjbqWF.jpg', 5),
('https://www.themoviedb.org/t/p/original/4LO6bnNGIa8zNbM6HwCYzlUKIHq.jpg', 5),
('https://www.themoviedb.org/t/p/original/ebl50buX9rp2gJlQm4yBt3TXJiU.jpg', 5),
('https://www.themoviedb.org/t/p/original/l6oCJ7odNlDzEkl4p9fviM4VxoR.jpg', 5),
('https://www.themoviedb.org/t/p/original/8f1pPxiH4F0qjuVBcEmaQAKKHZV.jpg', 5),
('https://www.themoviedb.org/t/p/original/zmzqvMJNw0dFNj0ndKX0aWL0MKF.jpg', 5),
('https://www.themoviedb.org/t/p/original/kVrrTRSZHSKcBfWadWWZnemk6Zh.jpg', 5),
('https://www.themoviedb.org/t/p/original/10HxxbUbGmuNIlFgg1sWFPfXF2e.jpg', 5),
('https://www.themoviedb.org/t/p/original/856sxm5kROfOBLe4UVSGJWqYU2i.jpg', 5),
('https://www.themoviedb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', 6),
('https://www.themoviedb.org/t/p/original/tnR3Og76RVIFUpb2mpi8Oi1GuAk.jpg', 6),
('https://www.themoviedb.org/t/p/original/ztZ4vw151mw04Bg6rqJLQGBAmvn.jpg', 6),
('https://www.themoviedb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg', 6),
('https://www.themoviedb.org/t/p/original/2HmLvOvu1rhfxK50WfJ4jFKy9zQ.jpg', 6),
('https://www.themoviedb.org/t/p/original/cPeny1AFySfq4BL9CKmY99wpRaO.jpg', 6),
('https://www.themoviedb.org/t/p/original/lQS7r7rl1zpQhYq1krKqQjwNFo1.jpg', 6),
('https://www.themoviedb.org/t/p/original/nkMvhad194v1sciF6b5pmGTr245.jpg', 6),
('https://www.themoviedb.org/t/p/original/tc6i0p0uXPaOJWflYzV72xlhEyo.jpg', 6),
('https://www.themoviedb.org/t/p/original/w4aiuhb2T8rOa5qnVfk20Ft9iRl.jpg', 6),
('https://www.themoviedb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg', 7),
('https://www.themoviedb.org/t/p/original/xHrp2pq73oi9D64xigPjWW1wcz1.jpg', 7),
('https://www.themoviedb.org/t/p/original/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg', 7),
('https://www.themoviedb.org/t/p/original/mY1cGRdH2UA0uDPP8ZdLjAN9N03.jpg', 7),
('https://www.themoviedb.org/t/p/original/4ke48uabb0K6uDcLlSED2ZvvYEb.jpg', 7),
('https://www.themoviedb.org/t/p/original/5P8SmMzSNYikXpxil6BYzJ16611.jpg', 7),
('https://www.themoviedb.org/t/p/original/jZfpDaku8fm14GZNc8lr7Li88Rm.jpg', 7),
('https://www.themoviedb.org/t/p/original/e66tM5YOawXLxhDAfWkR7sxpb3h.jpg', 7),
('https://www.themoviedb.org/t/p/original/9JVTQNCN4zUF0IfShUvsOFsmo1Q.jpg', 7),
('https://www.themoviedb.org/t/p/original/lqGqvmqHr8T2Ll8w7mzAtNshUpb.jpg', 7),
('https://image.tmdb.org/t/p/original/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg', 8),
('https://image.tmdb.org/t/p/original/9hNtTwY8P5v2MKnUeb7iuREI7Yb.jpg', 8),
('https://image.tmdb.org/t/p/original/zplntIhzXyBiXFYWReETxh0uyFF.jpg', 8),
('https://image.tmdb.org/t/p/original/yxkhM18dYwsRRffLnd9lz2d4i0v.jpg', 8),
('https://image.tmdb.org/t/p/original/bgaBKREAfUtZgvd6zoV6RQRcIUt.jpg', 8),
('https://image.tmdb.org/t/p/original/uqYxoj4hqwocwfBs2xxGyQT88Yk.jpg', 8),
('https://image.tmdb.org/t/p/original/qBx97wytqlyPqXATHqRgIVFxJRU.jpg', 8),
('https://image.tmdb.org/t/p/original/d6MhreFdMHONqX3iZlJGCF8UkIt.jpg', 8),
('https://image.tmdb.org/t/p/original/9inNotReApz0n50WvWbrt0n1cbL.jpg', 8),
('https://image.tmdb.org/t/p/original/pSOuqtJmdh7aI1yiK7M8e0PmbPC.jpg', 8),
('https://www.themoviedb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg', 9),
('https://www.themoviedb.org/t/p/original/AeK2MPOpYrOOgZNfFnfwp0L8tNn.jpg', 9),
('https://www.themoviedb.org/t/p/original/VlHt27nCqOuTnuX6bku8QZapzO.jpg', 9),
('https://www.themoviedb.org/t/p/original/aLQNKHhDLDdr81axLV1lF1X6Px6.jpg', 9),
('https://www.themoviedb.org/t/p/original/6BO9oackFxQPZhrpSLwT8fwgXCv.jpg', 9),
('https://www.themoviedb.org/t/p/original/uhYpkLSnlOXTQDmNnu1X4MHMt1S.jpg', 9),
('https://www.themoviedb.org/t/p/original/aRNMwIvEnYEMwGHLCAACyuq2I1K.jpg', 9),
('https://www.themoviedb.org/t/p/original/hn5TleW44PcZCejyz0BHdLch5yy.jpg', 9),
('https://www.themoviedb.org/t/p/original/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg', 9),
('https://www.themoviedb.org/t/p/original/5BjetzdVpWkPNKUIlpasnXVSwCP.jpg', 9),
('https://image.tmdb.org/t/p/original/yYrvN5WFeGYjJnRzhY0QXuo4Isw.jpg', 10),
('https://image.tmdb.org/t/p/original/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg', 10),
('https://image.tmdb.org/t/p/original/cs3LpA38BS2XDPfUzdgMB537XOo.jpg', 10),
('https://image.tmdb.org/t/p/original/6SGMzCsaU094Mt32IHGkIYtIl06.jpg', 10),
('https://image.tmdb.org/t/p/original/bty0TwJGsxMqYRptgyzn28Cxq5y.jpg', 10),
('https://image.tmdb.org/t/p/original/h2jp3CSdTPc22mUqps9I8vXDPaN.jpg', 10),
('https://image.tmdb.org/t/p/original/fSfWloWi5rmqbmC7GhO0HY2TMZW.jpg', 10),
('https://image.tmdb.org/t/p/original/vZujZnmkYB5nGUC5d5llK9DbGLk.jpg', 10),
('https://image.tmdb.org/t/p/original/8sMmAmN2x7mBiNKEX2o0aOTozEB.jpg', 10),
('https://image.tmdb.org/t/p/original/geI3Mk7nehX1kvyIY3K5ajaiNfI.jpg', 10);